### ISSUE TITLE
would you like to share your template and policy template files?

### ISSUE THREAD

**Issue by xiaolaipi1998** [CiscoDevNet/ansible-viptela#49]
I would like to use the playbook to control the vManage ,but I can't find the template and policy, could you share your sdn-templates for me ? thanks a lot

**Comment by stevenca** [comment]
Do you already have template and policy in your vmanage?  Generally, the easiest way is to export it with our python tool (https://github.com/ciscodevnet/python-viptela) as YAML and then import with the playbooks, changing where necessary.
