### ISSUE TITLE
Please assist with this issue: An exception occurred during task execution.

### ISSUE THREAD

**Issue by DelmiroCampelo** [CiscoDevNet/ansible-viptela#70]
Can you give me a hand with the issue below please? 
I'm having an issue with function "vmanage_device_attachment". When I run the playbook the result is failed=1, and throws the error below, but in vManage it actually completes the job successfully as expected. I'm trying to find out why it's giving me this error in Ansible and complete the task with ok=1 instead of a failure. Please see error attached. and Thank you for any help you can provide with this.

 
[vmanage_device_attachment_ERROR.txt](https://github.com/CiscoDevNet/ansible-viptela/files/8311919/vmanage_device_attachment_ERROR.txt)

**Comment by jasonking3** [comment]
I would need to dig into it more, but it looks like we are expecting the response to be JSON and it is not.  What parameters are you sending when you use the module?

**Comment by jasonking3** [comment]
Actually, I didn't see that this was posted in the ansible-viptela repo.  This repo is depricated and you should be using the ansible modules in python-viptela instead.  https://github.com/CiscoDevNet/python-viptela
